[".oh-my-zsh"]
    type = "archive"
    url = "https://github.com/ohmyzsh/ohmyzsh/archive/master.tar.gz"
    exact = true
    stripComponents = 1
[".oh-my-zsh/custom/plugins/zsh-syntax-highlighting"]
    type = "archive"
    url = "https://github.com/zsh-users/zsh-syntax-highlighting/archive/master.tar.gz"
    exact = true
    stripComponents = 1
{{ if ne .chezmoi.os "darwin" }}
{{- $fontFolder := ".local/share/fonts" -}}
{{- $suffix := "" -}}
{{- if eq .chezmoi.os "windows" -}}
{{-   $fontFolder = "AppData/Local/Microsoft/Windows/Fonts" -}}
{{-   $suffix = " Windows Compatible" -}}
{{- end -}}
# Download all the variants of the Fira Code Nerd Font
{{-   range $_, $face := list "Regular" "Light" "Medium" "Bold" "Retina" "SemiBold" -}}
{{-     range $_, $variant := list "" " Mono" }}
["{{ $fontFolder }}/Fira Code {{ $face }} Nerd Font Complete{{ $variant }}.ttf"]
    type = "file"
    url = "https://github.com/ryanoasis/nerd-fonts/raw/HEAD/patched-fonts/FiraCode/{{ $face }}/complete/Fira%20Code%20{{ $face }}%20Nerd%20Font%20Complete{{ $variant | replace " " "%20" }}{{ $suffix | replace " " "%20" }}.ttf"
{{      end -}}
{{-    end -}}
{{- end -}}
