[".oh-my-zsh"]
    type = "archive"
    url = "https://github.com/ohmyzsh/ohmyzsh/archive/master.tar.gz"
    exact = true
    stripComponents = 1
[".oh-my-zsh/custom/plugins/zsh-syntax-highlighting"]
    type = "archive"
    url = "https://github.com/zsh-users/zsh-syntax-highlighting/archive/master.tar.gz"
    exact = true
    stripComponents = 1

{{- /* Plover Grandjean dictionnaries */ -}}
{{- if and (not .devcontainer) (ne .chassistype "container") -}}
{{-   $ploverFolder := ".config/plover" -}}
{{-   if eq .chezmoi.os "darwin" -}}
{{-     $ploverFolder = "Library/Application Support/plover" -}}
{{-   else if eq .chezmoi.os "windows" -}}
{{-     $ploverFolder = "AppData/Local/plover/plover" -}}
{{-   end }}

# Download the Typey Type dictionaries from https://github.com/didoesdigital/steno-dictionaries
{{-   range $_, $dict := list "dict" "fingerspelling" "numbers" "punctuation" "emoji" "condensed-strokes" "condensed-strokes-fingerspelled" }}
["{{ $ploverFolder }}/{{ $dict }}.json"]
    type = "file"
    url = "https://github.com/didoesdigital/steno-dictionaries/raw/HEAD/dictionaries/{{ $dict | replace " " "%20" }}.json"
{{-   end }}

# Download the Plover Grandjean dictionaries from https://github.com/azizyemloul/plover-france-dict
{{-   range $_, $dict := list "01_French_SION" "02_French_Chiffres" "03_French_Adverbes" "04_French_Adjectifs" "05_French_Noms" "06_French_Verbes" "07_French_User" }}
["{{ $ploverFolder }}/{{ $dict }}.json"]
    type = "file"
    url = "https://github.com/azizyemloul/plover-france-dict/raw/HEAD/{{ $dict | replace " " "%20" }}.json"
{{-   end -}}
{{- end }}

{{- /* Fonts */ -}}
{{- if and (ne .chezmoi.os "darwin") (not .devcontainer) (ne .chassistype "container") -}}
{{-   $fontFolder := ".local/share/fonts" -}}
{{-   $suffix := "" -}}
{{-   if eq .chezmoi.os "windows" -}}
{{-     $fontFolder = "AppData/Local/Microsoft/Windows/Fonts" -}}
{{-     $suffix = " Windows Compatible" -}}
{{-   end }}

# Download all the variants of the Fira Code Nerd Font
{{-   range $_, $face := list "Regular" "Light" "Medium" "Bold" "Retina" "SemiBold" -}}
{{-     range $_, $variant := list "" " Mono" }}
["{{ $fontFolder }}/Fira Code {{ $face }} Nerd Font Complete{{ $variant }}.ttf"]
    type = "file"
    url = "https://github.com/ryanoasis/nerd-fonts/raw/HEAD/patched-fonts/FiraCode/{{ $face }}/complete/Fira%20Code%20{{ $face }}%20Nerd%20Font%20Complete{{ $variant | replace " " "%20" }}{{ $suffix | replace " " "%20" }}.ttf"
{{-     end -}}
{{-   end -}}
{{- end }}
