#!/bin/bash

# If not running interactively, don't do anything
if [[ -z "${PS1}" ]]; then
    return
fi

# Source global configuration between bash and zsh
if [[ -r "${HOME}/.shrc" ]]; then
    # shellcheck disable=SC1091
    source "${HOME}/.shrc"
fi

# Source global definitions
if [[ -r "/etc/bashrc" ]]; then
    # shellcheck disable=SC1091
    source "/etc/bashrc"
fi

# Bash completions on macOS
# https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/bash-completion%402.rb#L50
if [[ -r "/usr/local/etc/profile.d/bash_completion.sh" ]]; then
    # shellcheck disable=SC1091
    source "/usr/local/etc/profile.d/bash_completion.sh"
fi

# Don't put duplicate lines or lines starting with space in the history.
# See bash(1) for more options
HISTCONTROL=ignoreboth

# For setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=1000
HISTFILESIZE=2000

# Prompt
if command -v starship >/dev/null; then
    eval "$(starship init bash)"
fi
