#!/bin/bash

# If not running interactively, don't do anything
[ -z "${PS1}" ] && return

# Source global configuration between bash and zsh
if [[ -f "${HOME}/.shrc" ]]; then
    # shellcheck disable=SC1091
    source "${HOME}/.shrc"
fi

# Source global definitions
if [[ -f /etc/bashrc ]]; then
    # shellcheck disable=SC1091
    source /etc/bashrc
fi

# Don't put duplicate lines or lines starting with space in the history.
# See bash(1) for more options
HISTCONTROL=ignoreboth

# For setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=1000
HISTFILESIZE=2000

# Prompt
if command -v starship >/dev/null; then
    eval "$(starship init bash)"
fi
