#!/bin/bash
# If a hook with the same name exists in the local repository, execute it

GIT_ROOT="$(git rev-parse --show-superproject-working-tree --show-toplevel | head -1)"
HOOK_NAME="$(basename "$0")"
LOCAL_HOOK="${GIT_ROOT}/.git/hooks/${HOOK_NAME}"

if [[ -e "${LOCAL_HOOK}" ]]; then
    # shellcheck disable=SC1090
    source "${LOCAL_HOOK}"
fi
