(defun japanese-era-year (&optional year romaji)
  "Convert a gregorian year (the current one if `nil') to a Japanese era year."
  (let ((year-to-compute (if year
                           year
                           (string-to-number (format-time-string "%Y"))))
        (show-era (lambda (year era-start name-kanji name-romaji)
          (let ((era-name (if romaji (concat name-romaji " ") name-kanji)))
            (concat era-name (int-to-string (- year (1- era-start))))))))
    (pcase year-to-compute
      ((pred (<= 2019))
        (funcall show-era year-to-compute 2019 "令和" "Reiwa"))
      ((pred (<= 1989))
        (funcall show-era year-to-compute 1989 "平成" "Heisei"))
      ((pred (<= 1926))
        (funcall show-era year-to-compute 1926 "昭和" "Shōwa"))
      ((pred (<= 1912))
        (funcall show-era year-to-compute 1912 "大正" "Taishō"))
      ((pred (<= 1868))
        (funcall show-era year-to-compute 1868 "明治" "Meiji"))
      ((pred (<= 1865))
        (funcall show-era year-to-compute 1865 "慶応" "Keiō"))
      ((pred (<= 1864))
        (funcall show-era year-to-compute 1864 "元治" "Genji"))
      ((pred (<= 1861))
        (funcall show-era year-to-compute 1861 "文久" "Bunkyū"))
      ((pred (<= 1860))
        (funcall show-era year-to-compute 1860 "万延" "Man'en"))
      ((pred (<= 1854))
        (funcall show-era year-to-compute 1854 "安政" "Ansei"))
      ((pred (<= 1848))
        (funcall show-era year-to-compute 1848 "嘉永" "Kaei"))
      ((pred (<= 1844))
        (funcall show-era year-to-compute 1844 "弘化" "Kōka"))
      ((pred (<= 1830))
        (funcall show-era year-to-compute 1830 "天保" "Tenpō"))
      ((pred (<= 1818))
        (funcall show-era year-to-compute 1818 "文政" "Bunsei"))
      ((pred (<= 1804))
        (funcall show-era year-to-compute 1804 "文化" "Bunka"))
      ((pred (<= 1801))
        (funcall show-era year-to-compute 1801 "享和" "Kyōwa"))
      ((pred (<= 1789))
        (funcall show-era year-to-compute 1789 "寛政" "Kansei"))
      ((pred (<= 1781))
        (funcall show-era year-to-compute 1781 "天明" "Tenmei"))
      ((pred (<= 1772))
        (funcall show-era year-to-compute 1772 "安永" "An'ei"))
      ((pred (<= 1764))
        (funcall show-era year-to-compute 1764 "明和" "Meiwa"))
      ((pred (<= 1751))
        (funcall show-era year-to-compute 1751 "宝暦" "Hōreki"))
      ((pred (<= 1748))
        (funcall show-era year-to-compute 1748 "寛延" "Kan'en"))
      ((pred (<= 1744))
        (funcall show-era year-to-compute 1744 "延享" "Enkyō"))
      ((pred (<= 1741))
        (funcall show-era year-to-compute 1741 "寛保" "Kanpō"))
      ((pred (<= 1736))
        (funcall show-era year-to-compute 1736 "元文" "Genbun"))
      ((pred (<= 1716))
        (funcall show-era year-to-compute 1716 "享保" "Kyōhō"))
      ((pred (<= 1711))
        (funcall show-era year-to-compute 1711 "正徳" "Shōtoku"))
      ((pred (<= 1704))
        (funcall show-era year-to-compute 1704 "宝永" "Hōei"))
      ((pred (<= 1688))
        (funcall show-era year-to-compute 1688 "元禄" "Genroku"))
      ((pred (<= 1684))
        (funcall show-era year-to-compute 1684 "貞享" "Jōkyō"))
      ((pred (<= 1681))
        (funcall show-era year-to-compute 1681 "天和" "Tenna"))
      ((pred (<= 1673))
        (funcall show-era year-to-compute 1673 "延宝" "Enpō"))
      ((pred (<= 1661))
        (funcall show-era year-to-compute 1661 "寛文" "Kanbun"))
      ((pred (<= 1658))
        (funcall show-era year-to-compute 1658 "万治" "Manji"))
      ((pred (<= 1655))
        (funcall show-era year-to-compute 1655 "明暦" "Meireki"))
      ((pred (<= 1652))
        (funcall show-era year-to-compute 1652 "承応" "Jōō"))
      ((pred (<= 1648))
        (funcall show-era year-to-compute 1648 "慶安" "Keian"))
      ((pred (<= 1644))
        (funcall show-era year-to-compute 1644 "正保" "Shōhō"))
      ((pred (<= 1624))
        (funcall show-era year-to-compute 1624 "寛永" "Kan'ei"))
      ((pred (<= 1615))
        (funcall show-era year-to-compute 1615 "元和" "Genna"))
      (year-to-compute "Unknown"))))

(require 'calendar)

(defun japanese-year (year)
  "Display Japanese year for gregorian year YEAR."
  (interactive (list (read-number "Year: "
                       (string-to-number (format-time-string "%Y")))))
  (message "%s" (japanese-era-year year nil)))

(defun japanese-year-romaji (&optional year)
  "Display Japanese year (in rōmaji) for gregorian year YEAR."
  (interactive (list (read-number "Year: "
                       (string-to-number (format-time-string "%Y")))))
  (message "%s" (japanese-era-year year t)))

(defun calendar-japanese-year (&optional event)
  "Display Japanese year for date under cursor."
  (interactive (list last-nonmenu-event))
  (let ((year (nth 2 (calendar-cursor-to-date t event))))
    (message "%s" (japanese-era-year year nil))))

(defun calendar-japanese-year-romaji (&optional event)
  "Display Japanese year (in rōmaji) for date under cursor."
  (interactive (list last-nonmenu-event))
  (let ((year (nth 2 (calendar-cursor-to-date t event))))
    (message "%s" (japanese-era-year year t))))

(provide 'japanese-era)
