name: Install
on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - 'LICENSE'
      - 'README.md'
      - '.git*'
  push:
    branches:
      - master
    paths-ignore:
      - 'LICENSE'
      - 'README.md'
      - '.git*'
jobs:
  install:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Install chezmoi and the dotfiles
        run: ./install.sh --without-starship
        if: "!startsWith(matrix.os, 'windows')"
      - name: Install chezmoi and the dotfiles
        run: .\install.ps1 -WithoutStarship
        if: startsWith(matrix.os, 'windows')
      - name: Run chezmoi data
        run: '~/.local/bin/chezmoi data'
